### ISSUE TITLE
Why BVP have negative values?

### ISSUE THREAD

**Issue by xiyangxia** [cruiseresearchgroup/InGauge-and-EnGage-Datasets#1]
Why BVP-blood volume pulse have negative values?

**Comment by nancygaooo** [comment]
> Why BVP-blood volume pulse have negative values?

Hi xiyangxia, the negative values in blood volume pulse (BVP) data from Empatica E4 wristbands are usually due to the way the device processes and interprets the signal, not because the blood flow is negative. These values can appear because of baseline shifts in the signal, the relative nature of the measurements, or artifacts from movement and environmental factors. For more details please check:
https://support.empatica.com/hc/en-us/articles/360029719792-E4-data-BVP-expected-signal

**Comment by nancygaooo** [comment]
> Why BVP-blood volume pulse have negative values?

Hi xiyangxia, the negative values in blood volume pulse (BVP) data from Empatica E4 wristbands are usually due to the way the device processes and interprets the signal, not because the blood flow is negative. These values can appear because of baseline shifts in the signal, the relative nature of the measurements, or artifacts from movement and environmental factors. For more details please check:
https://support.empatica.com/hc/en-us/articles/360029719792-E4-data-BVP-expected-signal
